# Python CircleCI 2.1 configuration file
version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
  # using the latest pyhon orb
  python: circleci/python@2.1.1

jobs:
  build_and_test:
    executor: python/default 

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:    
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          command: |
            pytest --version
          name: Test
      - sonarcloud/scan
workflows:
  main:
    jobs:
      - build_and_test
